import React, { useState, useEffect, useCallback } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { apiFetch } from '../utils/api';

const buildSpfRecord = (provider) => {
  if (provider === 'vps') return 'v=spf1 a mx include:spf.mail.mailer-us.com ~all';
  if (provider === 'sparkpost') return 'v=spf1 include:sparkpostmail.com ~all';
  if (provider === 'brevo') return 'v=spf1 include:spf.brevo.com ~all';
  if (provider === 'azure') return 'v=spf1 include:spf.smtp2go.com ~all';
  return 'v=spf1 a mx ~all';
};
const buildDmarcRecord = (domain) => `v=DMARC1; p=none; rua=mailto:dmarc@${domain}; pct=100`;

export default function DomainDetailView({ onRefresh, onDeleteDomain }) {
  const { id: domainId } = useParams();
  const navigate = useNavigate();
  const [domain, setDomain] = useState(null);
  const [campaigns, setCampaigns] = useState([]);
  const [loading, setLoading] = useState(true);
  const [isVerifying, setIsVerifying] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [isDeleting, setIsDeleting] = useState(false);
  const [editData, setEditData] = useState(null);
  const [generatingDkim, setGeneratingDkim] = useState(false);
  const [copiedField, setCopiedField] = useState(null);
  const [testEmail, setTestEmail] = useState('');
  const [sendingTest, setSendingTest] = useState(false);
  const [expandedRecordId, setExpandedRecordId] = useState(null);

  const handleDelete = async () => {
    if (!window.confirm(`Are you sure you want to delete ${domain.domainName}? This action cannot be undone.`)) {
      return;
    }
    setIsDeleting(true);
    try {
      await onDeleteDomain(domainId);
      navigate('/domains');
    } catch {} finally {
      setIsDeleting(false);
    }
  };

  useEffect(() => {
    if (!domainId) return;
    setLoading(true);
    Promise.all([
      apiFetch(`/domains/${domainId}`),
      apiFetch('/campaigns')
    ]).then(([domainRes, campaignRes]) => {
      setDomain(domainRes.domain);
      setEditData({
        senderEmail: domainRes.domain.senderEmail,
        senderName: domainRes.domain.senderName,
        dailyLimit: domainRes.domain.dailyLimit,
        status: domainRes.domain.status,
        provider: domainRes.domain.provider || 'custom'
      });
      setCampaigns((campaignRes.campaigns || []).filter((c) =>
        (c.selectedDomains || []).some((d) =>
          (typeof d === 'string' ? d : d._id) === domainId
        )
      ));
    }).catch(() => {}).finally(() => setLoading(false));
  }, [domainId]);

  const handleVerify = async () => {
    setIsVerifying(true);
    try {
      const res = await apiFetch(`/domains/${domainId}/verify`, { method: 'POST' });
      setDomain(res.domain);
      setEditData((prev) => ({ ...prev, status: res.domain.status }));
    } catch {} finally {
      setIsVerifying(false);
    }
  };

  const handleSave = async () => {
    setIsSaving(true);
    try {
      const res = await apiFetch(`/domains/${domainId}`, {
        method: 'PUT',
        body: JSON.stringify(editData)
      });
      setDomain(res.domain);
      onRefresh();
    } catch {} finally {
      setIsSaving(false);
    }
  };

  const handleGenerateDkim = async () => {
    setGeneratingDkim(true);
    try {
      await apiFetch(`/domains/${domainId}/dkim/generate`, { method: 'POST' });
      const domainRes = await apiFetch(`/domains/${domainId}`);
      setDomain(domainRes.domain);
      onRefresh();
    } catch {} finally {
      setGeneratingDkim(false);
    }
  };

  const handleSendTest = async () => {
    if (!testEmail) return;
    setSendingTest(true);
    try {
      await apiFetch(`/domains/${domainId}/test-send`, {
        method: 'POST',
        body: JSON.stringify({ recipientEmail: testEmail })
      });
      setTestEmail('');
    } catch {} finally {
      setSendingTest(false);
    }
  };

  const copyToClipboard = useCallback(async (text, fieldName) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopiedField(fieldName);
      setTimeout(() => setCopiedField(null), 2500);
    } catch {}
  }, []);

  const handleDownloadZoneFile = () => {
    if (!domain) return;
    const spfRecord = buildSpfRecord();
    const dmarcRecord = buildDmarcRecord(domain.domainName);

    let content = `; DNS zone file records for ${domain.domainName}\n`;
    content += `; Generated by Mailer on ${new Date().toLocaleDateString()}\n\n`;
    content += `; SPF Record\n`;
    content += `@ 14400 IN TXT "${spfRecord}"\n\n`;
    content += `; DMARC Record\n`;
    content += `_dmarc 14400 IN TXT "${dmarcRecord.replace(/;/g, '\\;')}"\n`;

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${domain.domainName}-dns-zone.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center py-20">
        <div className="w-6 h-6 border-2 border-accent border-t-transparent rounded-full animate-spin" />
      </div>
    );
  }

  if (!domain) {
    return (
      <div className="text-center py-20">
        <p className="text-fg-muted text-sm">Domain not found.</p>
        <button onClick={() => navigate('/domains')} className="mt-4 text-accent text-sm font-medium hover:underline cursor-pointer" type="button">Go back</button>
      </div>
    );
  }

  const v = domain.verificationDetails;
  const usage = domain.dailyUsage || 0;
  const limit = domain.dailyLimit || 1;
  const usagePercent = Math.min(Math.round((usage / limit) * 100), 100);

  const statusStyles = {
    'Active': 'bg-success-muted text-success',
    'Pending Verification': 'bg-warning-muted text-warning',
    'Disabled': 'bg-error-muted text-error',
  };

  const provider = domain.provider || 'custom';
  const isBrevo = provider === 'brevo';
  const isSparkPost = provider === 'sparkpost';

  const spfRecord = buildSpfRecord(provider);
  const dmarcRecord = buildDmarcRecord(domain.domainName);

  const dkimSelector = isBrevo 
    ? 'mailin' 
    : isSparkPost 
      ? 'sparkpost' 
      : (provider === 'vps' ? 'postal-xxxx' : (domain.dkimSelector || 'default'));

  const dkimRecord = isBrevo
    ? 'Configure and copy DKIM key from your Brevo Dashboard'
    : isSparkPost
      ? 'Refer to SparkPost Sending Domains dashboard'
      : provider === 'vps'
        ? 'Copy the exact DKIM record from your Postal Web Interface -> Domains'
        : (domain.dkimPublicKey
            ? `v=DKIM1; k=rsa; p=${domain.dkimPublicKey}`
            : 'Generate DKIM keys below');

  const dkimHostname = `${dkimSelector}._domainkey`;
  const needsDkimGen = !isBrevo && !isSparkPost && provider !== 'vps' && !domain.dkimPublicKey;

  const dnsRecords = [
    {
      id: 'spf',
      type: 'TXT',
      name: '@',
      value: spfRecord,
      description: isBrevo
        ? 'Sender Policy Framework — authorizes Brevo to send emails on behalf of your domain'
        : isSparkPost
          ? 'Sender Policy Framework — authorizes SparkPost to send emails on behalf of your domain'
          : provider === 'azure'
            ? 'Sender Policy Framework — authorizes Azure Email Service to send emails on behalf of your domain'
            : 'Sender Policy Framework — authorizes Mailer to send emails on behalf of your domain',
      verified: v?.spf?.exists,
      liveValue: v?.spf?.record
    },
    {
      id: 'dkim',
      type: 'TXT',
      name: dkimHostname,
      value: dkimRecord,
      description: isBrevo
        ? 'DKIM is automatically handled by Brevo. Add the unique mailin._domainkey TXT record from your Brevo Console Senders & Domains settings.'
        : isSparkPost
          ? 'DKIM is managed by SparkPost. Refer to your SparkPost dashboard (Configuration > Sending Domains) to copy the exact DKIM record details.'
          : provider === 'vps'
            ? 'DKIM is managed by Postal. Copy the exact DKIM TXT record provided in the Postal web interface.'
            : 'DomainKeys Identified Mail — cryptographic signature to verify sender authenticity',
      verified: v?.dkim?.exists,
      liveValue: v?.dkim?.record,
      needsGeneration: needsDkimGen
    },
    {
      id: 'dmarc',
      type: 'TXT',
      name: `_dmarc.${domain.domainName}`,
      value: dmarcRecord,
      description: 'Domain-based Message Authentication — instructs providers what to do with failed authentication',
      verified: v?.dmarc?.exists,
      liveValue: v?.dmarc?.record
    }
  ];

  const verifiedCount = dnsRecords.filter(r => r.verified).length;
  const totalRecords = dnsRecords.length;

  return (
    <section className="flex flex-col pb-12 animate-fade-in">
      {/* Header */}
      <div className="flex items-center gap-3 mb-6">
        <button
          onClick={() => navigate('/domains')}
          className="w-9 h-9 flex items-center justify-center rounded-full bg-white border border-border-light text-fg-secondary hover:text-fg hover:bg-surface-secondary transition-all cursor-pointer"
          type="button"
          aria-label="Go back"
        >
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
            <polyline points="15 18 9 12 15 6" />
          </svg>
        </button>
        <div className="min-w-0 flex-1">
          <h1 className="text-xl font-bold tracking-tight text-fg">{domain.domainName}</h1>
          <p className="text-sm text-fg-muted">{domain.senderName} &lt;{domain.senderEmail}&gt;</p>
        </div>
        <span className={`text-[11px] font-semibold px-3 py-1 rounded-full ${statusStyles[domain.status] || 'bg-surface-secondary text-fg-muted'}`}>
          {domain.status}
        </span>
      </div>

      {/* Main Side-by-Side Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* Left Column (DNS Records - 2/3 width) */}
        <div className="lg:col-span-2 flex flex-col gap-6">
          {/* Progress Banner */}
          <div className="bg-white rounded-[24px] p-5 border border-border-light shadow-sm">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
              <div className="flex items-center gap-3">
                <div className={`w-9 h-9 rounded-full flex items-center justify-center flex-shrink-0 ${verifiedCount === totalRecords ? 'bg-green-50 text-green-600' : 'bg-amber-50 text-amber-600'}`}>
                  {verifiedCount === totalRecords ? (
                    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12" /></svg>
                  ) : (
                    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5"><circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="12"/><line x1="12" y1="16" x2="12.01" y2="16"/></svg>
                  )}
                </div>
                <div>
                  <h3 className="text-sm font-bold text-fg">
                    {verifiedCount === totalRecords
                      ? 'Domain Authenticated'
                      : `${verifiedCount} of ${totalRecords} Records Verified`}
                  </h3>
                  <p className="text-xs text-fg-muted mt-0.5">
                    {verifiedCount === totalRecords
                      ? 'Your DNS configuration is fully configured and ready for outbound sending.'
                      : 'Configure the DNS records below, then trigger validation.'}
                  </p>
                </div>
              </div>
              <div className="flex items-center gap-2 flex-shrink-0">
                <button
                  onClick={handleDownloadZoneFile}
                  className="inline-flex items-center gap-1.5 h-9 px-4 rounded-full text-xs font-bold bg-white border border-border-light text-fg-secondary hover:bg-surface-secondary transition-all cursor-pointer shadow-sm"
                  type="button"
                >
                  <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>
                  Download
                </button>
                <button
                  onClick={handleVerify}
                  disabled={isVerifying}
                  className="inline-flex items-center gap-1.5 h-9 px-4 rounded-full text-xs font-bold bg-[#131416] text-white hover:bg-accent-hover transition-all disabled:opacity-50 cursor-pointer shadow-sm"
                  type="button"
                >
                  <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" className={isVerifying ? 'animate-spin' : ''}>
                    <polyline points="23 4 23 10 17 10" /><polyline points="1 20 1 14 7 14" /><path d="M3.51 9a9 9 0 0114.85-3.36L23 10M1 14l4.64 4.36A9 9 0 0020.49 15" />
                  </svg>
                  {isVerifying ? 'Verifying...' : 'Verify'}
                </button>
              </div>
            </div>
            {/* Progress bar */}
            <div className="mt-3.5 h-2 bg-surface-secondary rounded-full overflow-hidden border border-border-light/30">
              <div
                className={`h-full rounded-full transition-all duration-500 ${verifiedCount === totalRecords ? 'bg-green-500' : 'bg-amber-500'}`}
                style={{ width: `${(verifiedCount / totalRecords) * 100}%` }}
              />
            </div>
          </div>

          {/* DNS Records Table */}
          <div className="bg-white rounded-[24px] border border-border-light shadow-sm overflow-hidden">
            <div className="overflow-x-auto">
              <table className="w-full text-left border-collapse">
                <thead>
                  <tr className="border-b border-border-light bg-surface-secondary/35 text-[10px] font-bold text-fg-muted uppercase tracking-wider select-none">
                    <th className="py-3 px-4 w-12 text-center">Status</th>
                    <th className="py-3 px-4 w-32">Type / Name</th>
                    <th className="py-3 px-4 w-1/4">Host</th>
                    <th className="py-3 px-4">Value</th>
                    <th className="py-3 px-4 w-12"></th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-border-light">
                  {dnsRecords.map((record) => {
                    const isExpanded = expandedRecordId === record.id;
                    return (
                      <React.Fragment key={record.id}>
                        <tr 
                          onClick={() => setExpandedRecordId(isExpanded ? null : record.id)}
                          className="hover:bg-surface-secondary/20 transition-colors cursor-pointer select-none"
                        >
                          <td className="py-3.5 px-4 text-center">
                            <div className="inline-flex items-center justify-center">
                              {record.verified ? (
                                <span className="w-5 h-5 rounded-full bg-green-50 text-green-600 flex items-center justify-center" title="Verified">
                                  <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12" /></svg>
                                </span>
                              ) : (
                                <span className="w-5 h-5 rounded-full bg-amber-50 text-amber-600 flex items-center justify-center" title="Pending Verification">
                                  <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5"><circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="12"/><line x1="12" y1="16" x2="12.01" y2="16"/></svg>
                                </span>
                              )}
                            </div>
                          </td>
                          <td className="py-3.5 px-4">
                            <div className="flex items-center gap-2">
                              <span className="px-1.5 py-0.5 rounded text-[9px] font-extrabold bg-surface-secondary text-fg-secondary border border-border-light/60">
                                {record.type}
                              </span>
                              <span className="text-xs font-bold text-fg">
                                {record.id.toUpperCase()}
                              </span>
                            </div>
                          </td>
                          <td className="py-3.5 px-4">
                            <div className="flex items-center gap-1.5 max-w-[200px]" onClick={e => e.stopPropagation()}>
                              <code className="text-xs font-mono text-fg bg-surface-secondary/60 rounded px-1.5 py-0.5 border border-border-light truncate" title={record.name}>
                                {record.name}
                              </code>
                              {!record.needsGeneration && (
                                <button
                                  onClick={() => copyToClipboard(record.name, `${record.id}-host`)}
                                  className="p-1 rounded text-fg-muted hover:text-fg hover:bg-surface-secondary transition-all cursor-pointer"
                                  type="button"
                                >
                                  {copiedField === `${record.id}-host` ? (
                                    <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3" className="text-green-600"><polyline points="20 6 9 17 4 12"/></svg>
                                  ) : (
                                    <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg>
                                  )}
                                </button>
                              )}
                            </div>
                          </td>
                          <td className="py-3.5 px-4">
                            <div className="flex items-center gap-1.5 max-w-xs sm:max-w-sm md:max-w-md" onClick={e => e.stopPropagation()}>
                              {record.needsGeneration ? (
                                <span className="text-xs text-amber-600 font-semibold bg-amber-50/50 px-2 py-0.5 rounded border border-amber-100">
                                  DKIM keys required
                                </span>
                              ) : (
                                <>
                                  <code className="text-xs font-mono text-fg bg-surface-secondary/60 rounded px-1.5 py-0.5 border border-border-light truncate flex-1" title={record.value}>
                                    {record.value}
                                  </code>
                                  <button
                                    onClick={() => copyToClipboard(record.value, `${record.id}-value`)}
                                    className="p-1 rounded text-fg-muted hover:text-fg hover:bg-surface-secondary transition-all cursor-pointer flex-shrink-0"
                                    type="button"
                                  >
                                    {copiedField === `${record.id}-value` ? (
                                      <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3" className="text-green-600"><polyline points="20 6 9 17 4 12"/></svg>
                                    ) : (
                                      <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg>
                                    )}
                                  </button>
                                </>
                              )}
                            </div>
                          </td>
                          <td className="py-3.5 px-4 text-right">
                            <svg 
                              width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"
                              className={`text-fg-muted transition-transform ${isExpanded ? 'rotate-180' : ''}`}
                            >
                              <polyline points="6 9 12 15 18 9" />
                            </svg>
                          </td>
                        </tr>
                        {isExpanded && (
                          <tr className="bg-surface-secondary/20 border-t border-border-light">
                            <td colSpan="5" className="p-5">
                              <div className="flex flex-col gap-4">
                                <div className="flex flex-col gap-1">
                                  <span className="text-[10px] font-bold text-fg-muted uppercase tracking-wider">Record Description</span>
                                  <p className="text-xs text-fg-secondary font-medium leading-relaxed">{record.description}</p>
                                  {record.priority && (
                                    <div className="mt-1.5 flex items-center gap-1.5 text-xs text-fg-secondary">
                                      <span className="font-bold">Priority:</span>
                                      <code className="bg-white border border-border-light rounded px-1.5 font-mono font-bold text-fg">{record.priority}</code>
                                    </div>
                                  )}
                                </div>
                                
                                {record.needsGeneration ? (
                                  <div className="p-4 rounded-xl bg-amber-50/50 border border-amber-200/60 flex items-center justify-between flex-wrap gap-3" onClick={e => e.stopPropagation()}>
                                    <div className="flex items-center gap-2">
                                      <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#d97706" strokeWidth="2.5"><rect x="3" y="11" width="18" height="11" rx="2" ry="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/></svg>
                                      <span className="text-xs font-bold text-amber-800">Generate DKIM cryptographic keys to activate this record.</span>
                                    </div>
                                    <button
                                      onClick={(e) => { e.stopPropagation(); handleGenerateDkim(); }}
                                      disabled={generatingDkim}
                                      className="inline-flex items-center gap-1.5 h-8 px-4 rounded-full text-xs font-bold bg-[#131416] text-white hover:bg-accent-hover transition-all disabled:opacity-50 cursor-pointer shadow-sm"
                                      type="button"
                                    >
                                      {generatingDkim ? (
                                        <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" className="animate-spin"><circle cx="12" cy="12" r="10"/><path d="M12 6v6l4 2"/></svg>
                                      ) : (
                                        <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5"><rect x="3" y="11" width="18" height="11" rx="2" ry="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/></svg>
                                      )}
                                      {generatingDkim ? 'Generating...' : 'Generate DKIM'}
                                    </button>
                                  </div>
                                ) : (
                                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                    <div className="bg-white rounded-xl p-4 border border-border-light shadow-sm flex flex-col justify-between" onClick={e => e.stopPropagation()}>
                                      <div>
                                        <div className="flex items-center justify-between mb-2">
                                          <span className="text-[10px] font-bold text-fg-secondary uppercase tracking-wider">Expected Value</span>
                                          <button
                                            onClick={() => copyToClipboard(record.value, `${record.id}-expected`)}
                                            className="inline-flex items-center gap-1 text-[10px] font-bold text-fg-muted hover:text-fg bg-surface-secondary/40 border border-border-light rounded-full px-2 py-0.5 transition-all cursor-pointer"
                                            type="button"
                                          >
                                            {copiedField === `${record.id}-expected` ? 'Copied' : 'Copy'}
                                          </button>
                                        </div>
                                        <code className="text-[11px] font-mono text-fg break-all leading-relaxed select-all">
                                          {record.value}
                                        </code>
                                      </div>
                                    </div>
                                    
                                    <div className={`rounded-xl p-4 border shadow-sm ${
                                      record.verified 
                                        ? 'bg-green-50/30 border-green-200/60' 
                                        : 'bg-amber-50/30 border-amber-200/60'
                                    }`}>
                                      <div className="flex items-center justify-between mb-2">
                                        <span className={`text-[10px] font-bold uppercase tracking-wider ${
                                          record.verified ? 'text-green-700' : 'text-amber-700'
                                        }`}>
                                          Current DNS Value
                                        </span>
                                        <span className={`text-[9px] font-bold px-2 py-0.5 rounded-full ${
                                          record.verified 
                                            ? 'bg-green-100 text-green-700' 
                                            : 'bg-amber-100 text-amber-700'
                                        }`}>
                                          {record.verified ? 'Match' : 'Mismatch'}
                                        </span>
                                      </div>
                                      
                                      {record.liveValue ? (
                                        <code className={`text-[11px] font-mono block break-all leading-relaxed ${
                                          record.verified ? 'text-green-700' : 'text-amber-800'
                                        }`}>
                                          {record.liveValue}
                                        </code>
                                      ) : (
                                        <p className="text-[11px] text-fg-muted italic">No records found on lookup.</p>
                                      )}
                                      
                                      {!record.verified && record.liveValue && (
                                        <p className="text-[10px] text-amber-700/80 font-semibold mt-2 leading-relaxed">
                                          Warning: Found record does not match expected value. Ensure spelling is correct and DNS has propagated.
                                        </p>
                                      )}
                                    </div>
                                  </div>
                                )}
                              </div>
                            </td>
                          </tr>
                        )}
                      </React.Fragment>
                    );
                  })}
                </tbody>
              </table>
            </div>
          </div>

          {/* Test Delivery Section */}
          {domain.verified && (
            <article className="bg-white rounded-[24px] p-5 shadow-sm border border-border-light">
              <h3 className="text-sm font-bold text-fg mb-3 flex items-center gap-2">
                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5"><line x1="22" y1="2" x2="11" y2="13"/><polygon points="22 2 15 22 11 13 2 9 22 2"/></svg>
                Test Delivery
              </h3>
              <p className="text-xs text-fg-muted mb-3">Send a test email to verify everything works end-to-end.</p>
              <div className="flex gap-2">
                <input
                  className="flex-1 h-10 px-4 bg-surface-secondary border border-border-light rounded-full outline-none text-xs text-fg placeholder:text-fg-muted focus:border-border focus:bg-white transition-all font-medium"
                  type="email"
                  placeholder="your@email.com"
                  value={testEmail}
                  onChange={(e) => setTestEmail(e.target.value)}
                />
                <button
                  onClick={handleSendTest}
                  disabled={sendingTest || !testEmail}
                  className="inline-flex items-center gap-1.5 h-10 px-5 rounded-full text-xs font-bold bg-[#131416] text-white hover:bg-accent-hover transition-all disabled:opacity-50 cursor-pointer flex-shrink-0 shadow-sm"
                  type="button"
                >
                  {sendingTest ? (
                    <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" className="animate-spin"><circle cx="12" cy="12" r="10"/><path d="M12 6v6l4 2"/></svg>
                  ) : (
                    <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5"><line x1="22" y1="2" x2="11" y2="13"/><polygon points="22 2 15 22 11 13 2 9 22 2"/></svg>
                  )}
                  {sendingTest ? 'Sending...' : 'Send Test'}
                </button>
              </div>
            </article>
          )}
        </div>

        {/* Right Column: Settings & Outbound Usage (1/3 width) */}
        <div className="flex flex-col gap-6">
          {/* Settings Form Card */}
          <article className="bg-white rounded-[24px] p-6 shadow-sm border border-border-light">
            <h3 className="text-sm font-bold text-fg mb-4 flex items-center gap-2 select-none">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-2 2 2 2 0 0 1-2-2v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83 0 2 2 0 0 1 0-2.83l.06-.06A1.65 1.65 0 0 0 4.68 15a1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1-2-2 2 2 0 0 1 2-2h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 0-2.83 2 2 0 0 1 2.83 0l.06.06A1.65 1.65 0 0 0 9 4.68a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 2-2 2 2 0 0 1 2 2v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 0 2 2 0 0 1 0 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 2 2 2 2 0 0 1-2 2h-.09a1.65 1.65 0 0 0-1.51 1z"/></svg>
              Domain Settings
            </h3>
            <div className="flex flex-col gap-4">
              <label className="flex flex-col gap-1.5">
                <span className="text-[10px] font-bold text-fg-secondary pl-1 uppercase tracking-wider">Sender Name</span>
                <input
                  className="w-full h-10 px-4 bg-surface-secondary border border-transparent rounded-full outline-none text-xs text-fg placeholder:text-fg-muted focus:border-border focus:bg-white focus:ring-2 focus:ring-accent/5 transition-all font-medium"
                  value={editData?.senderName || ''}
                  onChange={(e) => setEditData((prev) => ({ ...prev, senderName: e.target.value }))}
                />
              </label>
              <label className="flex flex-col gap-1.5">
                <span className="text-[10px] font-bold text-fg-secondary pl-1 uppercase tracking-wider">Sender Email</span>
                <input
                  className="w-full h-10 px-4 bg-surface-secondary border border-transparent rounded-full outline-none text-xs text-fg placeholder:text-fg-muted focus:border-border focus:bg-white focus:ring-2 focus:ring-accent/5 transition-all font-medium"
                  value={editData?.senderEmail || ''}
                  onChange={(e) => setEditData((prev) => ({ ...prev, senderEmail: e.target.value }))}
                />
                <span className="text-[10px] text-amber-600 font-medium leading-tight">
                  Must use @{domain.domainName} — Gmail requires DKIM alignment with the From address
                </span>
              </label>
              <label className="flex flex-col gap-1.5">
                <span className="text-[10px] font-bold text-fg-secondary pl-1 uppercase tracking-wider">Daily Limit</span>
                <input
                  className="w-full h-10 px-4 bg-surface-secondary border border-transparent rounded-full outline-none text-xs text-fg placeholder:text-fg-muted focus:border-border focus:bg-white focus:ring-2 focus:ring-accent/5 transition-all font-medium"
                  type="number"
                  min="1"
                  value={editData?.dailyLimit || ''}
                  onChange={(e) => setEditData((prev) => ({ ...prev, dailyLimit: Number(e.target.value) }))}
                />
              </label>
               <label className="flex flex-col gap-1.5">
                <span className="text-[10px] font-bold text-fg-secondary pl-1 uppercase tracking-wider">Status</span>
                <select
                  className="w-full h-10 px-4 bg-surface-secondary border border-transparent rounded-full outline-none text-xs text-fg focus:border-border focus:bg-white focus:ring-2 focus:ring-accent/5 transition-all font-medium cursor-pointer"
                  value={editData?.status || 'Pending Verification'}
                  onChange={(e) => setEditData((prev) => ({ ...prev, status: e.target.value }))}
                >
                  <option value="Active">Active</option>
                  <option value="Pending Verification">Pending Verification</option>
                  <option value="Disabled">Disabled</option>
                </select>
              </label>

              <label className="flex flex-col gap-1.5">
                <span className="text-[10px] font-bold text-fg-secondary pl-1 uppercase tracking-wider">SMTP Provider</span>
                <select
                  className="w-full h-10 px-4 bg-surface-secondary border border-transparent rounded-full outline-none text-xs text-fg focus:border-border focus:bg-white focus:ring-2 focus:ring-accent/5 transition-all font-medium cursor-pointer"
                  value={editData?.provider || 'custom'}
                  onChange={(e) => setEditData((prev) => ({ ...prev, provider: e.target.value }))}
                >
                  <option value="azure">Azure Email Service</option>
                  <option value="brevo">Brevo</option>
                  <option value="sparkpost">SparkPost</option>
                  <option value="vps">VPS (Postal)</option>
                  <option value="custom">Custom SMTP / Direct Sending</option>
                </select>
              </label>

              <button
                onClick={handleSave}
                disabled={isSaving || isDeleting}
                className="w-full inline-flex items-center justify-center h-10 px-6 rounded-full text-xs font-bold bg-[#131416] text-white hover:bg-accent-hover transition-all disabled:opacity-50 cursor-pointer shadow-sm mt-2 active:scale-[0.98]"
                type="button"
              >
                {isSaving ? 'Saving...' : 'Save Changes'}
              </button>

              <button
                onClick={handleDelete}
                disabled={isSaving || isDeleting}
                className="w-full inline-flex items-center justify-center h-10 px-6 rounded-full text-xs font-bold bg-white border border-rose-200 text-rose-600 hover:bg-rose-50 hover:border-rose-300 transition-all disabled:opacity-50 cursor-pointer shadow-sm mt-2 active:scale-[0.98] gap-1.5"
                type="button"
              >
                {isDeleting ? (
                  <div className="w-3.5 h-3.5 border-2 border-rose-600 border-t-transparent rounded-full animate-spin" />
                ) : (
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                    <polyline points="3 6 5 6 21 6" />
                    <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2" />
                  </svg>
                )}
                <span>Delete Domain</span>
              </button>
            </div>
          </article>

          {/* Usage Card */}
          <article className="bg-white rounded-[24px] p-6 shadow-sm border border-border-light">
            <h3 className="text-sm font-bold text-fg mb-4">Outbound Usage</h3>
            <div className="flex items-center justify-between mb-2">
              <span className="text-xs text-fg-secondary font-medium">Daily Limit Consumed</span>
              <span className="text-xs font-bold text-fg">{usage} / {limit}</span>
            </div>
            <div className="h-2 bg-surface-secondary rounded-full overflow-hidden border border-border-light/30">
              <div
                className={`h-full rounded-full transition-all duration-500 ${
                  usagePercent >= 90 ? 'bg-error' : usagePercent >= 70 ? 'bg-warning' : 'bg-[#131416]'
                }`}
                style={{ width: `${usagePercent}%` }}
              />
            </div>
            <p className="text-[10px] text-fg-muted mt-2 font-bold uppercase tracking-wider">{domain.totalEmailsSent || 0} total deliveries</p>
          </article>
        </div>
      </div>

      {/* Campaigns Section (full-width bottom) */}
      <article className="bg-white rounded-[24px] p-6 shadow-sm border border-border-light mt-6">
        <div className="flex items-center gap-2 mb-4">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" className="text-fg-secondary">
            <rect x="2" y="4" width="20" height="16" rx="2"/><path d="M22 7l-10 7L2 7"/>
          </svg>
          <h3 className="text-sm font-bold text-fg">Campaigns using this domain ({campaigns.length})</h3>
        </div>
        <div className="flex flex-col gap-3">
          {campaigns.length === 0 ? (
            <div className="text-center py-10 border border-dashed border-border-light rounded-[16px] bg-surface-secondary/20">
              <p className="text-xs font-bold text-fg-secondary">No campaigns yet</p>
              <p className="text-[10px] text-fg-muted mt-0.5">This domain hasn't been used in any active email campaigns.</p>
            </div>
          ) : (
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-3">
              {campaigns.map((c) => (
                <article key={c._id} className="flex items-center justify-between py-3 px-4 rounded-[16px] bg-white border border-border-light hover:border-border transition-all">
                  <div className="min-w-0">
                    <p className="text-xs font-bold text-fg truncate">{c.name}</p>
                    <p className="text-[10px] text-fg-muted mt-0.5">{c.recipients.length} recipients</p>
                  </div>
                  <span className={`text-[9px] font-bold px-2 py-0.5 rounded-full ${
                    c.status === 'Completed' ? 'bg-green-100 text-green-800' :
                    c.status === 'Running' ? 'bg-brand-lime-muted text-fg' :
                    'bg-amber-100 text-amber-800'
                  }`}>{c.status}</span>
                </article>
              ))}
            </div>
          )}
        </div>
      </article>
    </section>
  );
}
